name: Godot Checks ðŸ“Š
on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    paths:
      - "addons/**"
      - "scripts/**"

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-static
  cancel-in-progress: true

# global permissions
permissions: {}

jobs:
  godot-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: Scony/godot-gdscript-toolkit@master
      - name: Formatting checks
        run: gdformat --diff .
      - name: Linting checks
        run: gdlint .
      - name: Spell checks via codespell
        uses: codespell-project/actions-codespell@v2
        with:
          skip: ./addons,*.po
          ignore_words_list: chello,doubleclick,Manuel, SectionIn
